apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 6699
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dummy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-dummy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dummy
    spec:
      containers:
        - name: dummy
          image: "nginx:alpine"
          ports:
            - containerPort: 8081